version: '3.9'
services:
  gitlab-ci:
    image: gitlab/gitlab-ce:${GITLAB_CE_VERSION}
    restart: always
    hostname: "${GITLAB_HOSTNAME}"
    container_name: noc-gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "${GITLAB_EXTERNAL_URL}"
        gitlab_rails['initial_root_password'] = "${GITLAB_INIT_ROOT_PW}"
      TZ: "${TIMEZONE}"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - gitlab
      - toolchain

  gitlab-runner:
    image: gitlab/gitlab-runner:${GITLAB_RUNNER_VERSION}
    restart: always
    container_name: noc-gitlab-runner
    environment:
      TZ: "${TIMEZONE}"
    depends_on:
      - gitlab-ci
    volumes:
      - '$GITLAB_HOME/gitlab-runner:/etc/gitlab-runner'
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab
      - toolchain

networks:
  gitlab:
    name: gitlab-network
  toolchain:
    name: toolchain-network